<?php


namespace frontend\modules\user\widgets;

use yii\base\Widget;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\LoginForm;

class LoginWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        $login = new LoginForm();

         $form = ActiveForm::begin(['id' => 'login-form' , 'action' => '/user/login']); ?>

                <?= $form->field($login, 'email')->textInput(['autofocus' => true]) ?>

                <?= $form->field($login, 'password')->passwordInput() ?>

                <?= $form->field($login, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    Забыли пароль <?= Html::a('Сбросить', ['site/request-password-reset']) ?>.
                    <br>
                    Отправить письмо еще раз <?= Html::a('Отправить', ['site/resend-verification-email']) ?>
                </div>

                <div class="form-group">
                    <?= Html::submitButton('<i class="fa fa-user"></i> Войти', ['class' => 'in-cabinet', 'name' => 'login-button']) ?>
                    <a class="in-cabinet" data-toggle="modal" data-target="#modal-register" aria-hidden="true"  >
                        <i class="fa fa-user" ></i>
                        Регистрация
                    </a>
                </div>

                <?php ActiveForm::end();

        parent::run(); // TODO: Change the autogenerated stub
    }
}