<?php
namespace frontend\modules\user\widgets;

use frontend\modules\user\models\forms\SignupForm;
use yii\base\Widget;

use yii\helpers\Html;
use yii\widgets\ActiveForm;


class RegisterWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $signup = new SignupForm();

        $form = ActiveForm::begin(['id' => 'form-signup', 'action' => '/user/signup']);

        echo $form->field($signup, 'username')->textInput(['autofocus' => true]);

        echo $form->field($signup, 'email');

        echo $form->field($signup, 'password')->passwordInput();

        echo '<div class="form-group">';

        echo Html::submitButton('<i class="fa fa-user" ></i> Регистрация', ['class' => 'in-cabinet', 'name' =>
            'signup-button']);
        echo '</div>';

        ActiveForm::end();



    }
}