<?php
namespace frontend\modules\user\widgets;

use frontend\modules\user\models\forms\SignupForm;
use yii\base\Widget;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\Pol;

class RegisterWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $signup = new SignupForm();

        $pol = Pol::find()->asArray()->all();

        $form = ActiveForm::begin(['id' => 'form-signup', 'action' => '/user/signup']);

        echo $form->field($signup, 'username')->textInput(['autofocus' => true, 'placeholder' => 'Имя пользователя'])->label(false);

        echo $form->field($signup, 'email')->textInput(['placeholder' => 'Email'])->label(false);

        echo $form->field($signup, 'password')->passwordInput(['placeholder' => 'Пароль'])->label(false);

        echo $form ->field($signup, 'pol')->dropDownList(ArrayHelper::map($pol, 'id', 'value'));

        echo '<div class="form-group text-center">';

        echo Html::submitButton('Регистрация', ['class' => 'type-btn', 'name' =>
            'signup-button']);
        echo '</div>';

        ActiveForm::end();



    }
}