<?php


namespace chat\widgets;
use common\models\Presents;
use yii\base\Widget;

class PresentWidget extends Widget
{

    public $user_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        $data = Presents::find()->asArray()->all();

        return $this->render('present', [
                'data' => $data,
            ]
            );

    }
}