<?php


namespace frontend\widgets;

use Yii;
use yii\base\Widget;
use common\models\City;

class CityWidget extends Widget
{
    public function run()
    {

        if (isset(Yii::$app->controller->actionParams['city']) and $city = City::getCity(Yii::$app->controller->actionParams['city'])) {

            ?>

                <div class="place" data-toggle="modal" data-target="#cityModal" aria-hidden="true">
                    <span class="place-mobile"><i class="fas fa-location-arrow"></i></span>
                    <span class="place-desc">Местоположение : </span>
                    <span class="place-city"><?php echo $city['city'] ?></span>
                </div>

            <?php

        }

        parent::run(); // TODO: Change the autogenerated stub
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}