<?php


namespace frontend\widgets;

use frontend\modules\user\models\Profile;
use yii\base\Widget;

class PopularWidget extends Widget
{

    public $city;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        $popularUsers = Profile::getPopular();

        return $this->render('popular', [
            'popularUsers' => $popularUsers,
        ]);

    }
}