<?php


namespace frontend\widgets;

use yii\base\Widget;
use frontend\modules\user\models\Popular;

class PopularWidget extends Widget
{

    public $city;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        $popularUsers = Popular::find()->asArray()->orderBy('created_at DESC')->with('profile')->limit(6)->all();

        return $this->render('popular', [
            'popularUsers' => $popularUsers,
        ]);

    }
}