<?php


namespace frontend\widgets;
use common\models\Presents;
use common\models\PresentsCategory;
use frontend\models\relation\PresentToCategory;
use yii\base\Widget;
use yii\helpers\ArrayHelper;

class PresentWidget extends Widget
{

    public $user_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $present_category = PresentsCategory::find()->asArray()->all();

        $i = 0;

        $data = array();

        foreach ($present_category as $item){


            $ids = ArrayHelper::getColumn(PresentToCategory::find()->where(['category_id' => $item['id']])->asArray()->all(), 'present_id');
            $item['presents'] = Presents::find()->where(['in', 'id' , $ids])->asArray()->all();

            $data[$i][] = $item;

            $i++;

        }

        return $this->render('present', [
                'data' => $data,
                'user_id' => $this->user_id,
            ]
            );

    }
}