<?php


namespace frontend\widgets;
use common\models\Presents;
use common\models\PresentsCategory;
use frontend\models\relation\PresentToCategory;
use yii\base\Widget;
use yii\helpers\ArrayHelper;

class PresentWidget extends Widget
{

    public $user_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        $data = Presents::find()->asArray()->all();

        return $this->render('present', [
                'data' => $data,
                'user_id' => $this->user_id,
            ]
            );

    }
}