<?php


namespace frontend\widgets;

use yii\base\Widget;
use common\models\Age;
use common\models\BodyType;
use common\models\National;
use common\models\Place;
use common\models\Price;
use common\models\Service;
use Yii;
use common\models\Metro;
use common\models\Rayon;
use \common\models\Interesting;
use \common\models\Children;
use common\models\Family;
use common\models\CeliZnakomstvamstva;
use common\models\Smoking;
use common\models\Alcogol;
use frontend\components\helpers\AvailableHelper;

class SidebarWidget extends Widget
{

    private function getAvalibleIds(){

        if (isset (Yii::$app->params['result_id'])) return Yii::$app->params['result_id'];
        return false;

    }

    public function run()
    {

        $param = '';

        $placeList = AvailableHelper::getAvailable(Place::class, $this->getAvalibleIds());
        $metroList = AvailableHelper::getAvailable(Metro::class, $this->getAvalibleIds(), Yii::$app->controller->actionParams['city']);
        $rayonList = AvailableHelper::getAvailable(Rayon::class, $this->getAvalibleIds(), Yii::$app->controller->actionParams['city']);
        $ageList = AvailableHelper::getAvailable(Age::class, $this->getAvalibleIds());
        $priceList = AvailableHelper::getAvailable(Price::class, $this->getAvalibleIds());
        $nationalList = AvailableHelper::getAvailable(National::class, $this->getAvalibleIds());
        $bodyList = AvailableHelper::getAvailable(BodyType::class, $this->getAvalibleIds());
        $serviceList = AvailableHelper::getAvailable(Service::class, $this->getAvalibleIds());
        $interesi = AvailableHelper::getAvailable(Interesting::class, $this->getAvalibleIds());
        $deti = AvailableHelper::getAvailable(Children::class, $this->getAvalibleIds());
        $semeinoePolojenie = AvailableHelper::getAvailable(Family::class, $this->getAvalibleIds());
        $celiZnakomstva = AvailableHelper::getAvailable(CeliZnakomstvamstva::class, $this->getAvalibleIds());
        $smoke = AvailableHelper::getAvailable(Smoking::class, $this->getAvalibleIds());
        $alcogol = AvailableHelper::getAvailable(Alcogol::class, $this->getAvalibleIds());


        if (isset(Yii::$app->controller->actionParams['param'])) $param =
            $this->prepereParam(Yii::$app->controller->actionParams['param']);

        return $this->render('sidebar', [
            'placeList' => $placeList,
            'ageList' => $ageList,
            'priceList' => $priceList,
            'nationalList' => $nationalList,
            'bodyList' => $bodyList,
            'serviceList' => $serviceList,
            'metroList' => $metroList,
            'rayonList' => $rayonList,
            'interesi' => $interesi,
            'deti' => $deti,
            'semeinoePolojenie' => $semeinoePolojenie,
            'celiZnakomstva' => $celiZnakomstva,
            'smoke' => $smoke,
            'alcogol' => $alcogol,
            'param' => $param,
        ]);
    }

    private function prepereParam($param){

        return explode('/',$param);

    }

    public function init()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }

}