<?php


namespace frontend\widgets;

use frontend\modules\chat\components\helpers\GetDialogsHelper;
use Yii;
use yii\base\Widget;


class UserSideBarWidget extends Widget
{

    public $form_id = 'addpostform-image';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        $countNotRead = GetDialogsHelper::getNotReadCount(Yii::$app->user->id);

        return $this->render('user-sidebar', [
            'form_id' => $this->form_id,
            'countNotRead' => $countNotRead
        ]);

        parent::run(); // TODO: Change the autogenerated stub
    }
}