<?php


namespace frontend\widgets;

use yii\base\Widget;


class UserSideBarWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {

        return $this->render('user-sidebar');

        parent::run(); // TODO: Change the autogenerated stub
    }
}