<?php


namespace frontend\modules\user\controllers;

use frontend\modules\user\models\Profile;
use yii\web\Controller;
use Yii;

class EditController extends Controller
{

    public function beforeAction($action)
    {

        if (Yii::$app->user->isGuest)  {

            Yii::$app->response->redirect('/', 301)->send();

            exit();

        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionEditProfile($city){

        $model = Profile::findOne(Yii::$app->user->id);

        return $this->render('edit_profile', [
            'model' => $model,
        ] );

    }
    public function actionEditAnket($city){

        return $this->render('edit' );

    }
}