<?php


namespace frontend\modules\user\controllers;

use frontend\modules\user\components\helpers\TimeHelper;
use frontend\modules\user\models\Profile;
use yii\web\Controller;
use Yii;

class EditController extends Controller
{

    public function beforeAction($action)
    {

        if (Yii::$app->user->isGuest)  {

            Yii::$app->response->redirect('/', 301)->send();

            exit();

        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionEditProfile($city){

        $model = Profile::findOne(Yii::$app->user->id);

        if (Yii::$app->request->isPost){

            $data = Yii::$app->request->post();

            $data['Profile']['birthday'] = TimeHelper::getTimestampFromString($data['Profile']['birthday']) + 3600 * 12;

            if ($model->load($data) and $model->save()) {

                Yii::$app->session->setFlash('success', "Данные обновлены");

                return $this->redirect('/user');
            }else{
                Yii::$app->session->setFlash('warning', "Ошибка");
            }

        }

        return $this->render('edit_profile', [
            'model' => $model,
        ] );

    }
    public function actionEditAnket($city){

        return $this->render('edit' );

    }
}